#logging:
#  level:
#    org.springframework.web: ERROR
#    com.serverside.module.servicebazarbd: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    path: /home/partho/Desktop/Logger/api1.log